{"variants":[{"paths":["\/documentation\/authfoundation\/oauth2servererror\/localizederror-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":2,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OAuth2ServerError\/LocalizedError-Implementations","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"No overview available."}],"kind":"article","metadata":{"modules":[{"name":"AuthFoundation"}],"role":"collectionGroup","title":"LocalizedError Implementations"},"hierarchy":{"paths":[["doc:\/\/AuthFoundation\/documentation\/AuthFoundation","doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OAuth2ServerError"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OAuth2ServerError\/errorDescription-3vcs","doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OAuth2ServerError\/failureReason","doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OAuth2ServerError\/helpAnchor","doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OAuth2ServerError\/recoverySuggestion"],"generated":true}],"references":{"doc://AuthFoundation/documentation/AuthFoundation":{"role":"collection","title":"AuthFoundation","abstract":[{"type":"text","text":"Library that provides foundational features used by Oktaâ€™s authentication libraries, as well as APIs used to work with tokens and user credentials."}],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation","kind":"symbol","type":"topic","url":"\/documentation\/authfoundation"},"doc://AuthFoundation/documentation/AuthFoundation/OAuth2ServerError/helpAnchor":{"role":"symbol","title":"helpAnchor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"helpAnchor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OAuth2ServerError\/helpAnchor","kind":"symbol","type":"topic","url":"\/documentation\/authfoundation\/oauth2servererror\/helpanchor"},"doc://AuthFoundation/documentation/AuthFoundation/OAuth2ServerError":{"role":"symbol","title":"OAuth2ServerError","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"OAuth2ServerError"}],"abstract":[],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OAuth2ServerError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OAuth2ServerError"}],"url":"\/documentation\/authfoundation\/oauth2servererror"},"doc://AuthFoundation/documentation/AuthFoundation/OAuth2ServerError/failureReason":{"role":"symbol","title":"failureReason","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"failureReason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OAuth2ServerError\/failureReason","kind":"symbol","type":"topic","url":"\/documentation\/authfoundation\/oauth2servererror\/failurereason"},"doc://AuthFoundation/documentation/AuthFoundation/OAuth2ServerError/recoverySuggestion":{"role":"symbol","title":"recoverySuggestion","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recoverySuggestion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OAuth2ServerError\/recoverySuggestion","kind":"symbol","type":"topic","url":"\/documentation\/authfoundation\/oauth2servererror\/recoverysuggestion"},"doc://AuthFoundation/documentation/AuthFoundation/OAuth2ServerError/errorDescription-3vcs":{"role":"symbol","title":"errorDescription","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OAuth2ServerError\/errorDescription-3vcs","kind":"symbol","type":"topic","url":"\/documentation\/authfoundation\/oauth2servererror\/errordescription-3vcs"}}}