{"variants":[{"paths":["\/documentation\/authfoundation\/credentialerror\/localizederror-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":2,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/CredentialError\/LocalizedError-Implementations","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"No overview available."}],"kind":"article","metadata":{"modules":[{"name":"AuthFoundation"}],"role":"collectionGroup","title":"LocalizedError Implementations"},"hierarchy":{"paths":[["doc:\/\/AuthFoundation\/documentation\/AuthFoundation","doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/CredentialError"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/CredentialError\/errorDescription-8zc9g","doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/CredentialError\/errorDescription-s9qz","doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/CredentialError\/failureReason","doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/CredentialError\/helpAnchor","doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/CredentialError\/recoverySuggestion"],"generated":true}],"references":{"doc://AuthFoundation/documentation/AuthFoundation/CredentialError/errorDescription-8zc9g":{"role":"symbol","title":"errorDescription","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/CredentialError\/errorDescription-8zc9g","kind":"symbol","type":"topic","url":"\/documentation\/authfoundation\/credentialerror\/errordescription-8zc9g"},"doc://AuthFoundation/documentation/AuthFoundation/CredentialError/recoverySuggestion":{"role":"symbol","title":"recoverySuggestion","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recoverySuggestion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/CredentialError\/recoverySuggestion","kind":"symbol","type":"topic","url":"\/documentation\/authfoundation\/credentialerror\/recoverysuggestion"},"doc://AuthFoundation/documentation/AuthFoundation/CredentialError/helpAnchor":{"role":"symbol","title":"helpAnchor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"helpAnchor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/CredentialError\/helpAnchor","kind":"symbol","type":"topic","url":"\/documentation\/authfoundation\/credentialerror\/helpanchor"},"doc://AuthFoundation/documentation/AuthFoundation/CredentialError":{"role":"symbol","title":"CredentialError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CredentialError"}],"abstract":[{"type":"text","text":"Errors that may occur in the process of managing credentials."}],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/CredentialError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CredentialError"}],"url":"\/documentation\/authfoundation\/credentialerror"},"doc://AuthFoundation/documentation/AuthFoundation":{"role":"collection","title":"AuthFoundation","abstract":[{"type":"text","text":"Library that provides foundational features used by Oktaâ€™s authentication libraries, as well as APIs used to work with tokens and user credentials."}],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation","kind":"symbol","type":"topic","url":"\/documentation\/authfoundation"},"doc://AuthFoundation/documentation/AuthFoundation/CredentialError/errorDescription-s9qz":{"role":"symbol","title":"errorDescription","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/CredentialError\/errorDescription-s9qz","kind":"symbol","type":"topic","url":"\/documentation\/authfoundation\/credentialerror\/errordescription-s9qz"},"doc://AuthFoundation/documentation/AuthFoundation/CredentialError/failureReason":{"role":"symbol","title":"failureReason","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"failureReason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/CredentialError\/failureReason","kind":"symbol","type":"topic","url":"\/documentation\/authfoundation\/credentialerror\/failurereason"}}}