{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"missingCoordinator"}],"languages":["swift"],"platforms":["macOS"]}]}],"schemaVersion":{"major":0,"minor":2,"patch":0},"sections":[],"variants":[{"paths":["\/okta-mobile-swift/development/AuthFoundation/documentation\/authfoundation\/credentialerror\/missingcoordinator"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/AuthFoundation\/okta-mobile-swift/development/AuthFoundation/documentation\/AuthFoundation\/CredentialError\/missingCoordinator","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Thrown when a credential no longer has a weak reference to the coordinator that was used to create it."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"missingCoordinator"}],"title":"CredentialError.missingCoordinator","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"s:14AuthFoundation15CredentialErrorO18missingCoordinatoryA2CmF","modules":[{"name":"AuthFoundation"}]},"hierarchy":{"paths":[["doc:\/\/AuthFoundation\/okta-mobile-swift/development/AuthFoundation/documentation\/AuthFoundation","doc:\/\/AuthFoundation\/okta-mobile-swift/development/AuthFoundation/documentation\/AuthFoundation\/CredentialError"]]},"references":{"doc://AuthFoundation/okta-mobile-swift/development/AuthFoundation/documentation/AuthFoundation":{"role":"collection","title":"AuthFoundation","abstract":[{"type":"text","text":"Library that provides foundational features used by Oktaâ€™s authentication libraries, as well as APIs used to work with tokens and user credentials."}],"identifier":"doc:\/\/AuthFoundation\/okta-mobile-swift/development/AuthFoundation/documentation\/AuthFoundation","kind":"symbol","type":"topic","url":"\/okta-mobile-swift/development/AuthFoundation/documentation\/authfoundation"},"doc://AuthFoundation/okta-mobile-swift/development/AuthFoundation/documentation/AuthFoundation/CredentialError/missingCoordinator":{"role":"symbol","title":"CredentialError.missingCoordinator","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"missingCoordinator"}],"abstract":[{"type":"text","text":"Thrown when a credential no longer has a weak reference to the coordinator that was used to create it."}],"identifier":"doc:\/\/AuthFoundation\/okta-mobile-swift/development/AuthFoundation/documentation\/AuthFoundation\/CredentialError\/missingCoordinator","kind":"symbol","type":"topic","url":"\/okta-mobile-swift/development/AuthFoundation/documentation\/authfoundation\/credentialerror\/missingcoordinator"},"doc://AuthFoundation/okta-mobile-swift/development/AuthFoundation/documentation/AuthFoundation/CredentialError":{"role":"symbol","title":"CredentialError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CredentialError"}],"abstract":[{"type":"text","text":"Errors that may occur in the process of managing credentials."}],"identifier":"doc:\/\/AuthFoundation\/okta-mobile-swift/development/AuthFoundation/documentation\/AuthFoundation\/CredentialError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CredentialError"}],"url":"\/okta-mobile-swift/development/AuthFoundation/documentation\/authfoundation\/credentialerror"}}}