{"seeAlsoSections":[{"title":"Error Types","identifiers":["doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/APIClientError","doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OAuth2ServerError","doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OktaAPIError","doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/CredentialError","doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/TokenError","doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/JWTError","doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/KeychainError","doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/AuthenticationError"],"generated":true}],"schemaVersion":{"major":0,"minor":2,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OAuth2Error"}],"title":"OAuth2Error","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"s:14AuthFoundation11OAuth2ErrorO","modules":[{"name":"AuthFoundation"}],"navigatorTitle":[{"kind":"identifier","text":"OAuth2Error"}]},"abstract":[{"type":"text","text":"Errors that may occur when interacting with OAuth2 endpoints."}],"sections":[],"identifier":{"url":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OAuth2Error","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/AuthFoundation\/10Foundation14LocalizedErrorP","doc:\/\/AuthFoundation\/s5ErrorP","doc:\/\/AuthFoundation\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/AuthFoundation\/documentation\/AuthFoundation"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OAuth2Error\/cannotComposeUrl","doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OAuth2Error\/error(_:)","doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OAuth2Error\/invalidUrl","doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OAuth2Error\/missingClientConfiguration","doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OAuth2Error\/missingLocationHeader","doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OAuth2Error\/missingToken(type:)","doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OAuth2Error\/network(error:)","doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OAuth2Error\/oauth2Error(code:description:)","doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OAuth2Error\/signatureInvalid"]},{"title":"Default Implementations","identifiers":["doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OAuth2Error\/Error-Implementations","doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OAuth2Error\/LocalizedError-Implementations"],"generated":true}],"variants":[{"paths":["\/documentation\/authfoundation\/oauth2error"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OAuth2Error"}],"languages":["swift"],"platforms":["macOS"]}]}],"references":{"doc://AuthFoundation/documentation/AuthFoundation/OAuth2Error/LocalizedError-Implementations":{"role":"collectionGroup","title":"LocalizedError Implementations","abstract":[],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OAuth2Error\/LocalizedError-Implementations","kind":"article","type":"topic","url":"\/documentation\/authfoundation\/oauth2error\/localizederror-implementations"},"doc://AuthFoundation/documentation/AuthFoundation/OAuth2Error/cannotComposeUrl":{"role":"symbol","title":"OAuth2Error.cannotComposeUrl","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cannotComposeUrl"}],"abstract":[],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OAuth2Error\/cannotComposeUrl","kind":"symbol","type":"topic","url":"\/documentation\/authfoundation\/oauth2error\/cannotcomposeurl"},"doc://AuthFoundation/documentation/AuthFoundation/OAuth2ServerError":{"role":"symbol","title":"OAuth2ServerError","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"OAuth2ServerError"}],"abstract":[{"type":"text","text":"Describes errors reported from an OAuth2 server."}],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OAuth2ServerError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OAuth2ServerError"}],"url":"\/documentation\/authfoundation\/oauth2servererror"},"doc://AuthFoundation/documentation/AuthFoundation/OAuth2Error/oauth2Error(code:description:)":{"role":"symbol","title":"OAuth2Error.oauth2Error(code:description:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"oauth2Error"},{"kind":"text","text":"("},{"kind":"externalParam","text":"code"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OAuth2Error\/oauth2Error(code:description:)","kind":"symbol","type":"topic","url":"\/documentation\/authfoundation\/oauth2error\/oauth2error(code:description:)"},"doc://AuthFoundation/documentation/AuthFoundation":{"role":"collection","title":"AuthFoundation","abstract":[{"type":"text","text":"Library that provides foundational features used by Oktaâ€™s authentication libraries, as well as APIs used to work with tokens and user credentials."}],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation","kind":"symbol","type":"topic","url":"\/documentation\/authfoundation"},"doc://AuthFoundation/documentation/AuthFoundation/OAuth2Error/error(_:)":{"role":"symbol","title":"OAuth2Error.error(_:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OAuth2Error\/error(_:)","kind":"symbol","type":"topic","url":"\/documentation\/authfoundation\/oauth2error\/error(_:)"},"doc://AuthFoundation/documentation/AuthFoundation/OAuth2Error/Error-Implementations":{"role":"collectionGroup","title":"Error Implementations","abstract":[],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OAuth2Error\/Error-Implementations","kind":"article","type":"topic","url":"\/documentation\/authfoundation\/oauth2error\/error-implementations"},"doc://AuthFoundation/documentation/AuthFoundation/OAuth2Error":{"role":"symbol","title":"OAuth2Error","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"OAuth2Error"}],"abstract":[{"type":"text","text":"Errors that may occur when interacting with OAuth2 endpoints."}],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OAuth2Error","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OAuth2Error"}],"url":"\/documentation\/authfoundation\/oauth2error"},"doc://AuthFoundation/documentation/AuthFoundation/OAuth2Error/network(error:)":{"role":"symbol","title":"OAuth2Error.network(error:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"network"},{"kind":"text","text":"("},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"APIClientError","preciseIdentifier":"s:14AuthFoundation14APIClientErrorO"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OAuth2Error\/network(error:)","kind":"symbol","type":"topic","url":"\/documentation\/authfoundation\/oauth2error\/network(error:)"},"doc://AuthFoundation/documentation/AuthFoundation/OAuth2Error/missingLocationHeader":{"role":"symbol","title":"OAuth2Error.missingLocationHeader","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"missingLocationHeader"}],"abstract":[],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OAuth2Error\/missingLocationHeader","kind":"symbol","type":"topic","url":"\/documentation\/authfoundation\/oauth2error\/missinglocationheader"},"doc://AuthFoundation/documentation/AuthFoundation/APIClientError":{"role":"symbol","title":"APIClientError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"APIClientError"}],"abstract":[{"type":"text","text":"Errors that may occur at the API or network level."}],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/APIClientError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"APIClientError"}],"url":"\/documentation\/authfoundation\/apiclienterror"},"doc://AuthFoundation/documentation/AuthFoundation/OAuth2Error/missingToken(type:)":{"role":"symbol","title":"OAuth2Error.missingToken(type:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"missingToken"},{"kind":"text","text":"("},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Token","preciseIdentifier":"s:14AuthFoundation5TokenC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Kind","preciseIdentifier":"s:14AuthFoundation5TokenC4KindO"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OAuth2Error\/missingToken(type:)","kind":"symbol","type":"topic","url":"\/documentation\/authfoundation\/oauth2error\/missingtoken(type:)"},"doc://AuthFoundation/documentation/AuthFoundation/CredentialError":{"role":"symbol","title":"CredentialError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CredentialError"}],"abstract":[{"type":"text","text":"Errors that may occur in the process of managing credentials."}],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/CredentialError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CredentialError"}],"url":"\/documentation\/authfoundation\/credentialerror"},"doc://AuthFoundation/documentation/AuthFoundation/JWTError":{"role":"symbol","title":"JWTError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"JWTError"}],"abstract":[{"type":"text","text":"Describes errors that may occur with parsing or validating JWT tokens."}],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/JWTError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"JWTError"}],"url":"\/documentation\/authfoundation\/jwterror"},"doc://AuthFoundation/documentation/AuthFoundation/AuthenticationError":{"role":"symbol","title":"AuthenticationError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthenticationError"}],"abstract":[{"type":"text","text":"Errors that may be generated during the process of authenticating with a variety of authentication flows."}],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/AuthenticationError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AuthenticationError"}],"url":"\/documentation\/authfoundation\/authenticationerror"},"doc://AuthFoundation/documentation/AuthFoundation/OktaAPIError":{"role":"symbol","title":"OktaAPIError","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"OktaAPIError"}],"abstract":[{"type":"text","text":"Describes errors that may be reported from an Okta API endpoint."}],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OktaAPIError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"OktaAPIError"}],"url":"\/documentation\/authfoundation\/oktaapierror"},"doc://AuthFoundation/documentation/AuthFoundation/TokenError":{"role":"symbol","title":"TokenError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TokenError"}],"abstract":[{"type":"text","text":"Describes errors that may occur when working with tokens."}],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/TokenError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TokenError"}],"url":"\/documentation\/authfoundation\/tokenerror"},"doc://AuthFoundation/documentation/AuthFoundation/KeychainError":{"role":"symbol","title":"KeychainError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"KeychainError"}],"abstract":[{"type":"text","text":"Describes errors that may occur when interacting with the keychain."}],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/KeychainError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"KeychainError"}],"url":"\/documentation\/authfoundation\/keychainerror"},"doc://AuthFoundation/10Foundation14LocalizedErrorP":{"type":"unresolvable","title":"Foundation.LocalizedError","identifier":"doc:\/\/AuthFoundation\/10Foundation14LocalizedErrorP"},"doc://AuthFoundation/documentation/AuthFoundation/OAuth2Error/missingClientConfiguration":{"role":"symbol","title":"OAuth2Error.missingClientConfiguration","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"missingClientConfiguration"}],"abstract":[],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OAuth2Error\/missingClientConfiguration","kind":"symbol","type":"topic","url":"\/documentation\/authfoundation\/oauth2error\/missingclientconfiguration"},"doc://AuthFoundation/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/AuthFoundation\/s8SendableP"},"doc://AuthFoundation/documentation/AuthFoundation/OAuth2Error/signatureInvalid":{"role":"symbol","title":"OAuth2Error.signatureInvalid","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"signatureInvalid"}],"abstract":[],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OAuth2Error\/signatureInvalid","kind":"symbol","type":"topic","url":"\/documentation\/authfoundation\/oauth2error\/signatureinvalid"},"doc://AuthFoundation/documentation/AuthFoundation/OAuth2Error/invalidUrl":{"role":"symbol","title":"OAuth2Error.invalidUrl","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidUrl"}],"abstract":[],"identifier":"doc:\/\/AuthFoundation\/documentation\/AuthFoundation\/OAuth2Error\/invalidUrl","kind":"symbol","type":"topic","url":"\/documentation\/authfoundation\/oauth2error\/invalidurl"},"doc://AuthFoundation/s5ErrorP":{"type":"unresolvable","title":"Swift.Error","identifier":"doc:\/\/AuthFoundation\/s5ErrorP"}}}